CREATE TABLE IF NOT EXISTS ISSUES (
  id INT PRIMARY KEY,
  description VARCHAR(500) NOT NULL,
  parent_id VARCHAR(250) NOT NULL,
  issue_status VARCHAR(10) NOT NULL,
  creation_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  log_link VARCHAR(250) NOT NULL
);